spring:
  data:
    mongodb:
      uri: mongodb://root:rhleh2160@localhost/mprDB?authSource=admin
      database: mprDB
      username: root
      password: rhleh2160
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher